name: flutter_application_1
description: "Good Taste Restaurant App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2


  # Utilitaires
  provider: ^6.1.1
  image_picker: ^0.8.7+1
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  http: ^1.3.0  # Version mise à jour pour résoudre le conflit
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_ui_auth: ^1.2.0
  flutter_bloc: ^8.1.3

  # Packages Firebase supplémentaires
  firebase_ui_firestore: ^1.2.0
  firebase_ui_oauth: ^1.2.0
  firebase_ui_oauth_google: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/restaurant_interior.jpg
    - assets/images/
    - assets/images/Entrées/
    - assets/images/plats/
    - assets/images/desserts/
    - assets/images/boissons/
    - assets/images/Accompagnements/