# Generated by Django 5.1.6 on 2025-04-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nomCat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idC', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=128)),
                ('isGuest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('idE', models.AutoField(primary_key=True, serialize=False)),
                ('nomE', models.CharField(max_length=100)),
                ('prénomE', models.CharField(max_length=100)),
                ('usernameE', models.CharField(max_length=100, unique=True)),
                ('adresseE', models.CharField(max_length=200)),
                ('motDePasseE', models.CharField(max_length=128)),
                ('rôle', models.CharField(choices=[('CUISINIER', 'Cuisinier'), ('SERVEUR', 'Serveur'), ('MANAGER', 'Manager')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('idDep', models.AutoField(primary_key=True, serialize=False)),
                ('dateDep', models.DateField()),
                ('totaleDep', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('idIng', models.AutoField(primary_key=True, serialize=False)),
                ('nomIng', models.CharField(max_length=100)),
                ('nbrMax', models.IntegerField()),
                ('nbrMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idM', models.AutoField(primary_key=True, serialize=False)),
                ('nomMenu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MontantEncaisse',
            fields=[
                ('idMontant', models.AutoField(primary_key=True, serialize=False)),
                ('dateMontant', models.DateField()),
                ('totalEncaissé', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('idT', models.AutoField(primary_key=True, serialize=False)),
                ('nbrPersonne', models.IntegerField()),
                ('etatTable', models.CharField(choices=[('libre', 'Libre'), ('reservee', 'Réservée'), ('occupee', 'Occupée')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCmd', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('livree', 'Livrée')], max_length=20)),
                ('confirmation', models.BooleanField(default=False)),
                ('idC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisinier',
            fields=[
                ('idE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.employe')),
                ('dateEmbauche', models.DateField()),
                ('niveauExperience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('idE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.employe')),
                ('dateEmbauche', models.DateField()),
                ('zoneAffectation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fidelite',
            fields=[
                ('idF', models.AutoField(primary_key=True, serialize=False)),
                ('pointsFidélité', models.IntegerField(default=0)),
                ('SeuilVIP', models.IntegerField(default=100)),
                ('idC', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('estimation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField()),
                ('ingrédients', models.JSONField(default=dict)),
                ('quantité', models.IntegerField(default=1)),
                ('idCat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plat')),
            ],
            options={
                'unique_together': {('idM', 'idP')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='plats',
            field=models.ManyToManyField(through='core.Menu_Plat', to='core.plat'),
        ),
        migrations.CreateModel(
            name='Commande_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.IntegerField(default=1)),
                ('idCmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commande')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plat')),
            ],
            options={
                'unique_together': {('idCmd', 'idP')},
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='plats',
            field=models.ManyToManyField(through='core.Commande_Plat', to='core.plat'),
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('idRapport', models.AutoField(primary_key=True, serialize=False)),
                ('dateRapport', models.DateField()),
                ('beneficeNet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idDep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depenses')),
                ('idMontant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.montantencaisse')),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('idR', models.AutoField(primary_key=True, serialize=False)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('idC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plat')),
                ('idR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recommandation')),
            ],
            options={
                'unique_together': {('idR', 'idP')},
            },
        ),
        migrations.AddField(
            model_name='recommandation',
            name='plats',
            field=models.ManyToManyField(through='core.Recommandation_Plat', to='core.plat'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False)),
                ('capacitéS', models.IntegerField()),
                ('SeuilAlerte', models.IntegerField()),
                ('idIng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idRes', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('idC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('idT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('idE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.employe')),
                ('idRapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rapportfinancier')),
            ],
        ),
        migrations.CreateModel(
            name='Serveur_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commande')),
                ('idE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serveur')),
            ],
            options={
                'unique_together': {('idE', 'idCmd')},
            },
        ),
        migrations.AddField(
            model_name='serveur',
            name='commandes',
            field=models.ManyToManyField(through='core.Serveur_Commande', to='core.commande'),
        ),
        migrations.CreateModel(
            name='Cuisinier_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateField()),
                ('derniereMAJ', models.DateField()),
                ('idM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
                ('idE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuisinier')),
            ],
            options={
                'unique_together': {('idE', 'idM')},
            },
        ),
    ]
